name: "Deploy b3lb documentation"

on: 
  workflow_dispatch:

  pull_request:
    branches:
     - main

  push:
    branches:
     - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: make dirhtml
        pre-build-command: pip install -r requirements.txt ; find .
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/dirhtml/
    - name: Publish documentation
      if: github.event_name == 'push'
      run: |
        git clone https://github.com/DE-IBH/b3lb-docs.git --branch gh-pages --single-branch gh-pages
        cp -r docs/build/dirhtml/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      if: github.event_name == 'push'
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
